--- #YAML:1.0
name:               Dancer-Session-CHI
version:            0.1.0
abstract:           Sessions stored in a CHI-based cache
author:
    - Richard Huxton <richard.huxton@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CHI:         0
    Dancer:      0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
