---
abstract: 'CHI-based session engine for Dancer'
author:
  - 'Richard Simões <rsimoes at cpan dot org>'
build_requires:
  Dancer: 0
  Dancer::Test: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Most: 0.22
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-CHI
requires:
  CHI: 0.49
  Dancer::Config: 0
  Dancer::Logger: 0
  Dancer::Plugin::Cache::CHI: 0
  Dancer::Session::Abstract: 0
  English: 0
  Moose: 2.0205
  MooseX::ClassAttribute: 0.26
  MooseX::NonMoose: 0.22
  namespace::autoclean: 0.13
  perl: 5.008
  strictures: 1
  utf8: 0
resources:
  bugtracker: https://github.com/rsimoes/dancer-session-chi/issues
  homepage: https://metacpan.org/release/Dancer-Session-CHI
  repository: git://github.com/rsimoes/dancer-session-chi.git
version: v0.1.1
